# pre-commit run --all-files
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v0.730
#     hooks:
#     -   id: mypy
#         args: [--ignore-missing-imports]
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.3
    hooks:
    -   id: seed-isort-config
        args: [--application-directories=app]
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort
# -   repo: https://github.com/psf/black
#     rev: 19.3b0
#     hooks:
#     -   id: black
