language: python
python:
  - "2.7"
install: 
  - pip install natsort matplotlib coveralls
  - pip install shapely
  - pip install mysql-python
  - pip install future
script:
  - nosetests --with-coverage
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install libblas-dev liblapack-dev gfortran
  - sudo apt-get install python-scipy python-numpy
script:
  - nosetests --with-cov --cover-package hwrt --logging-level=INFO
after_success:
  - coveralls