language: python
python:
  - "2.7"
install: 
  - pip install --use-mirrors pyparsing
  - pip install --use-mirrors matplotlib
  - pip install natsort
  - pip install matplotlib
script: nosetests
virtualenv:
  system_site_packages: true
before_install:
  - pip install numpy
  - pip install python-dateutil
  - pip install pytz
  - pip install scipy
  - pip install numpy
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
script: nosetests
after_success:
  - coveralls